### ISSUE TITLE
[JuniorDevSG Jan 2020]: Lessons from coding a old-new app: Slack for Win 3.1

### ISSUE THREAD

**Issue by yeokm1** [JuniorDevSingapore/meetups#1]
**Title**: Lessons from coding a old-new app: Slack for Win 3.1
 
**Date(s)**: 14 Jan 2020

**Description**: 

I built a Win 3.1 app during a company hackathon. 

Without the benefit of modern libraries and languages, I had to read up and take care of many low level details, socket programming, HTTP, JSON parsing, UI design in code all under tight memory constraints. Nevertheless, it was a terrific lesson in understanding how things work under the hood.

I'll share my learnings and process for how an old-new app can be created with the aid of modern tools and hindsight of old technologies. And perhaps what lessons can it offer us today.

http://yeokhengmeng.com/2019/12/building-a-new-win-3-1-app-in-2019-part-1-slack-client/
https://github.com/yeokm1/w31slack

It was Number 1 on Hacker news for a few hours! :) 
https://news.ycombinator.com/item?id=21831951

**Profile**: 
I work as an IoT Engineer as SP Digital in the day. Outside of work, I like to repair things and fly private planes for fun. Occasionally, I dabble with retrocomputing stuff.

**LinkedIn/Twitter/GitHub/Social media page**: 
https://www.facebook.com/yeokhengmeng
https://github.com/yeokm1/
https://twitter.com/yeokm1
https://www.linkedin.com/in/yeokhengmeng/

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Video presentation: https://engineers.sg/v/3920
