### ISSUE TITLE
[Event] Pro tips for builders on AWS

### ISSUE THREAD

**Issue by gabehollombe-aws** [JuniorDevSingapore/meetups#11]
**Title**: Pro Tips for Builders on AWS
 
**Date(s)**: Whenever's good for ya'll.  Sometime in July perhaps?

**Description**: 

This talk will feature a list of quick-hitting tips aimed at improving your day-to-day life building on AWS. I'll cover working effectively with the AWS CLI and other third-party CLIs; creating, editing, debugging, and deploying an AWS Lambda-powered serverless applications quickly and easily using the new AWS Toolkit which works with VS code and other IDEs; and introducing the concept of structured logging and how to perform powerful filtering and searches on your structured application logs with Amazon CloudWatch. 

The talk also has some fun history lessons that have nothing to do with AWS, so even if you're not into the cloud, you might enjoy learning a bit about the history of CLIs, IDEs, and logging data.

**Profile**: 

Hello! I'm Gabe and I work as a Developer Advocate at AWS, where I try to stay up-to-date on new technology and share what I'm learning with the world. 

**LinkedIn/Twitter/GitHub/Social media page**: You can find me on Twitter or LinkedIn at @gabehollombe

**Comment by yishus** [comment]
hey @gabehollombe-aws we have narrowed down the dates for the next meetup to be on 16 July 8pm. Would this date time work for you?

**Comment by gabehollombe** [comment]
Yes! That date works well for me, thanks!
-g

**Comment by yishus** [comment]
cool! the meetup's page over here https://www.meetup.com/Junior-Developers-Singapore/events/271450434/ and let's keep in touch

**Comment by gabehollombe-aws** [comment]
Right on!  See you then! =-D

**Comment by miccheng** [comment]
Done.

**Comment by miccheng** [comment]
Video of presentation: https://engineers.sg/v/4067
