### ISSUE TITLE
[Event] KopiRun - from idea to app launch

### ISSUE THREAD

**Issue by alyssaong1** [JuniorDevSingapore/meetups#12]
**Title**: KopiRun - from idea to app launch
 
**Date(s)**: September 2020

**Description**: 
Thinking of building your first mobile app? Well, now you can do it using the same language that powers the web!

Come along to this talk to find out about the creation of KopiRun, an app that helps you find people nearby who could help do coffee runs for you (think carpooling but for food/groceries). We'll be talking about important things to think about before you launch your app, the tech stack that went behind KopiRun, and some key decisions and takeaways out of our journey from the first line of code to putting the app on the app store. 

**Profile**: 

Speakers: Alyssa Ong and Zane Chua

Alyssa's Profile:
Alyssa is a (newly turned) Technical Program Manager who also very much enjoys coding. Alyssa has a diverse portfolio of skills ranging from mobile and web UI design to cloud architecture design, app dev and DevOps. During her free time, she works on KopiRun, plays Dota and drinks lots of bubble tea. 

Zane's Profile:
Zane primarily focused on web application projects as a full-stack developer before graduating from the University of Glasgow with a degree in Computer Science. Zane has experience in launching his own start-up and SaaS product which lead to a side interest in open-source code. He maintains a few open-source products/projects in his free time.

Over the past few years, he has polished his skills over multiple projects handling both front end and backend development with a recent focus in mobile app development and developer operations.

**LinkedIn/Twitter/GitHub/Social media page**: 
https://twitter.com/alyssaong1337
https://github.com/alyssaong1

https://twitter.com/zanejchua
https://github.com/zanechua
https://linkedin.com/in/zanejchua/

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Video of the talk: https://engineers.sg/v/4116
