### ISSUE TITLE
[JuniorDevSG Jan 2020]: Exploring Seasonal Insights from Singapore Weather Station Data

### ISSUE THREAD

**Issue by hweecat** [JuniorDevSingapore/meetups#2]
**Title**: Exploring Seasonal Insights from Singapore Weather Station Data
 
**Date(s)**: 14 January 2020

**Description**: 
Most of the world experience the four seasons, but how many seasons does a tropical country like Singapore have? We can get such insights from publicly-available weather data; however, we need to write scripts to make API requests for retrieving the data needed for analysis.

In this talk, I will be sharing about my approach in scraping Singapore weather station data from Data.gov.sg APIs for a user-defined time period. With the extracted data, I will also be using a data-driven approach to investigate the weather trends and seasons over the past few years, and explore how these insights could help us in predicting future weather trends.

https://github.com/hweecat/api_scraping_nea_datasets

**Profile**: 
Ong Chin Hwee is a data engineer, aspiring polymath and Industry 4.0 enthusiast who happens to be interested in things that fly (and stuff that burn to keep things flying). One of Chin Hwee's latest projects involves contributing to the documentation for pandas, an open-source Python library that is immensely useful for anything related to data.

**LinkedIn/Twitter/GitHub/Social media page**:
https://twitter.com/ongchinhwee
https://linkedin.com/in/ongchinhwee

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Video presentation: https://engineers.sg/v/3919
