### ISSUE TITLE
JuniorDev SG  Jan 2020 <Lighthouse techniques for debugging web>

### ISSUE THREAD

**Issue by Calebyang93** [JuniorDevSingapore/meetups#3]
Title: Lighthouse techniques for debugging web applications on chrome 
 
**Date(s)**: 14 January 2020

**Description**:  TBC 

*You may wish to provide links to your website, slides, past events, social media, etc.*

Slides:  https://docs.google.com/presentation/d/1lLDKgEUKwzLV0U-3eszm5i-DIbTOLpTfCmjiI8BGxDA/edit?usp=sharing (TBC)

**Profile**: 

*A short self-intro*:  Web Frontend Developer doing freelance work. Had experience with C#, javascript, html, css and a bit of java in work stints at Tata Consultancy Services, Bookmyshow and Kee Link. Currently looking for a frontend developer role.

**LinkedIn/Twitter/GitHub/Social media page**: 
1. linkedin: https://www.linkedin.com/in/caleb-yang-14786137/
2. github: https://github.com/Calebyang93
**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Video presentation: https://engineers.sg/v/3918
