### ISSUE TITLE
[JuniorDevSG Jan 2020]: My Journey Into Tech

### ISSUE THREAD

**Issue by pehyuhan** [JuniorDevSingapore/meetups#4]
**Title**: My Journey Into Tech
 
**Date(s)**: 14 Jan 2020

**Description**: 
I’ll share my personal journey into tech - the motivations, considerations and challenges along the way.

**Profile**: 
I work as a software engineer in Sephora SEA. During my free time, i enjoy swimming and shopping :)

**LinkedIn/Twitter/GitHub/Social media page**: 
https://www.facebook.com/peh.yuhan
https://www.linkedin.com/in/pehyuhan

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Video presentation: https://engineers.sg/v/3917
