### ISSUE TITLE
[Event]:<Mozilla's Project Things - A Secure and Private Smart Home IoT Gateway>

### ISSUE THREAD

**Issue by apvenks** [JuniorDevSingapore/meetups#5]
**Title**: *Mozilla's Project Things - A Secure and Private Smart Home IoT Gateway*
 
**Date(s)**: *13 March 2020*

**Description**: Mozilla's Project things is a software distribution for smart home gateways focused on privacy, security and interoperability. This session also covers how to build your own IoT device using the Web Thing API and how developers can contribute to Mozilla's mission.

*check out to know more about https://iot.mozilla.org/*

**Profile**: Professionally I am an IoT Architect, but passionately I am a Mozilla Representative and an active IEEE member in SG contributing to various FOSS projects and volunteering several tech events.

**LinkedIn/Twitter/GitHub/Social media page**: 
*https://www.linkedin.com/in/apvenkat/*
*https://mozillians.org/en-US/u/apvenkat/*

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
Probably we'll do this another time. Thanks for your interest.
