### ISSUE TITLE
[Event] My journey joining Stripe as a new grad engineer

### ISSUE THREAD

**Issue by dwee-stripe** [JuniorDevSingapore/meetups#7]
**Title**: My journey joining Stripe as a new grad engineer
 
**Date(s)**: 13 Feb 2020

**Description**: 
I joined Stripe six months ago as a new grad engineer here in Singapore. This is my first role as a full-time engineer in a rapidly growing tech company, with new programming languages, new financial domain knowledge and new patterns, culture and otherwise. It has been a challenging but very rewarding and interesting process that I would like to share!

**Profile**: 

*A short self-intro*
I work as a software engineer building global payments infrastructure at Stripe. I enjoy working on challenges of scale and helping to build a better payments product for our many users. During my free time, I enjoy running and watching British panel shows like QI and Would I Lie to You!

**LinkedIn/Twitter/GitHub/Social media page**: *URL where people can find out more about you online.*
www.github.com/darrenwee 
www.linkedin.com/in/darrenweezy

**Requirements** *(check any that apply)*:

- [x] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
https://www.meetup.com/Junior-Developers-Singapore/events/268369921/
