### ISSUE TITLE
[Event] Building Web3 - Introduction to blockchain and smart contracts

### ISSUE THREAD

**Issue by edison0xyz** [JuniorDevSingapore/meetups#8]
**Title**: *Building Web3 - introduction to blockchain and smart contracts*
 
**Date(s)**: *13 March 2020*

**Description**: 

Blockchain is a topic of great interest, and it has the potential to radically change the economy that we know of today. At the core is the idea is decentralised application - which consists of smart contracts that could connect any developers to a network of global liquidity through public blockchain network. Blockchain and smart contract could potentially be more efficient in bringing together multiple parties to work together, automating process flow and bringing efficiency through automated pieces of pre-agreed logic called smart contract. 

Agenda:

- What is blockchain?
- What are decentralised apps and how they are different from other apps
- Getting started with smart contract programming and dApp development

**Profile**: 

Edison is a software engineer who specialises in blockchains, web application and data. He has spent the last three years on blockchain development and has experience working on Ethereum, Hyperledger Fabric and Zilliqa blockchain. In his past roles, he has built a security tokenisation technology, custody software and token exchange. 

Edison is currently the Head of Engineering at Aqilliz - a Singapore-based marketing technology company which aims to make marketing more efficient and transparent. Before joining Aqilliz, Edison is the Application Engineering Lead and the first application engineer at Zilliqa, a Singapore-based high-throughput and secure public blockchain platform. Zilliqa is the first to implement sharding, a technology that improves the transactional capacity of a public blockchain network and is famous for the creation of a new smart contract programming language called Scilla.

Edison holds an M.Sc from Carnegie Mellon University and is an avid guitarist and amateur cook.

https://twitter.com/EdisonLimjh
https://www.linkedin.com/in/edisonljh/
https://github.com/edisonljh

**Requirements** *(check any that apply)*:

- [ ] I do not wish to have my talk recorded for Engineers.SG

**Comment by miccheng** [comment]
@edisonljh Are you still keen on speaking?

**Comment by miccheng** [comment]
Video of presentation: https://engineers.sg/v/4003
